version: '3.8'

services:
  # The SQL Database Container
  db:
    image: postgres:15-alpine
    container_name: sentinel-db
    restart: always
    environment:
      - POSTGRES_USER=sentinel_admin
      - POSTGRES_PASSWORD=sentinel_pass
      - POSTGRES_DB=sentinel_logs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # The Dashboard & Backend Container
  sentinel:
    build:
      context: .
    container_name: zkteco-sentinel
    depends_on:
      - db
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=db
      - DB_USER=sentinel_admin
      - DB_PASSWORD=sentinel_pass
      - DB_NAME=sentinel_logs
      - DB_PORT=5432
    restart: always

volumes:
  pgdata: